--CRIAÇÃO BANCO DE DADOS (BD)
CREATE DATABASE Senatur_Tarde;

--UTILIZAR O BD
USE Senatur_Tarde;

--CRIAÇÃO DE TABELAS DO BANCO DE DADOS
CREATE TABLE Pacotes (
	IdPacote	INT PRIMARY KEY IDENTITY,
	NomePacote	VARCHAR(255) NOT NULL UNIQUE,
	Descricao	VARCHAR(1220) NOT NULL,
	DataIda		DATE NOT NULL,
	DataVolta	DATE NOT NULL,
	Valor		DECIMAL(18,2) NOT NULL,
	Ativo		BIT DEFAULT (1) NOT NULL,
	NomeCidade	VARCHAR(255) NOT NULL);
GO
CREATE TABLE TiposUsuario (
	IdTipoUsuario	INT PRIMARY KEY IDENTITY,
	Titulo			VARCHAR (255)NOT NULL);
GO
CREATE TABLE Usuarios (
	IdUsuario		INT PRIMARY KEY IDENTITY,
	Email			VARCHAR (255) NOT NULL UNIQUE,
	Senha			VARCHAR (150) NOT NULL,
	IdTipoUsuario	INT FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario));
GO